server:
  port: 8080
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:db}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_DB_USERNAME:root}
    password: ${POSTGRES_DB_PASSWORD:root}
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:db}
    user: ${POSTGRES_DB_USERNAME:root}
    password: ${POSTGRES_DB_PASSWORD:root}

joust:
  security:
    jwt-token:
      secret: secret
      validity: 3600000
